import requests
import json
import pickle



m={'Accept':'application/json','authorization':'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImMzMmRlODIyLTBlZTgtNDQ5Ny1iNTI1LWZlODNmOTgwYjZmMCIsImlhdCI6MTYyNjc3MzMxNiwic3ViIjoiZGV2ZWxvcGVyLzY2NWM2MDI3LTFlOTctYjczMC1lYWQ1LTlmYWE0NDgyYTY4ZiIsInNjb3BlcyI6WyJicmF3bHN0YXJzIl0sImxpbWl0cyI6W3sidGllciI6ImRldmVsb3Blci9zaWx2ZXIiLCJ0eXBlIjoidGhyb3R0bGluZyJ9LHsiY2lkcnMiOlsiMTcxLjc4LjE2OS40NiIsIjI3LjU3LjYzLjIiXSwidHlwZSI6ImNsaWVudCJ9XX0.WxuLZNBnFIjVuvc4FnvrgfAbjWjvQGAyQRgh_gCF6ehSbPIMfhILpa8haeCVSyhO2IjjuSK7pZs9F65bgP4iYA'}

b=requests.get(r'https://api.brawlstars.com/v1/clubs/%23202U9UPLU/members',headers=m) # %23 - js '#'

dic=b.json()
	
print([i for i in dic['items']])


